### ISSUE TITLE
国服最新版，弹不出来天赋框

### ISSUE THREAD

**Issue by biankobe24** [cangzhang/champ-r#109]
选择英雄后弹不出来。。。安装的是1.1.9版本
[2021-11-03 00:56:35.619] [info]  ChampR starting, app version 1.1.9.
[2021-11-03 00:56:35.796] [info]  System locale is zh-CN, app lang is zh-CN
[2021-11-03 00:56:35.796] [info]  init lockfile watcher, dir: D:\LOL\英雄联盟
[2021-11-03 00:56:35.841] [info]  shouldAppendGameToDir:  true lolDirHasCJKChar:  true
[2021-11-03 00:56:35.844] [info]  [watcher] got auth
[2021-11-03 00:56:35.861] [error] (node:18164) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `ChampR --trace-warnings ...` to show where the warning was created)
[2021-11-03 00:56:35.866] [info]  [watcher] got auth
[2021-11-03 00:56:35.879] [info]  [ws] handle lcu message improperly:  Unexpected end of JSON input
[2021-11-03 00:56:36.865] [info]  userId: bada458466f3e4320dc0e9540e2a160541301eca28faa5f6960973c2053d8146
[2021-11-03 00:56:36.865] [info]  Checking for update
[2021-11-03 00:56:36.865] [info]  Checking update...
[2021-11-03 00:56:41.632] [info]  app sha is 022cfbd

[2021-11-03 00:56:58.751] [error] Error: Error: net::ERR_CONNECTION_RESET
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
[2021-11-03 00:56:58.752] [error] Error in auto-updater. Error: net::ERR_CONNECTION_RESET
[2021-11-03 00:56:58.752] [error] Network Error

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/releases/tag/v1.1.9
