### ISSUE TITLE
v11.23更新后不可以自动弹出天赋界面

### ISSUE THREAD

**Issue by chickes** [cangzhang/champ-r#113]
v11.23更新后不可以自动弹出天赋界面

**Comment by magicwenli** [comment]
`LeagueClient`目录下的`lockfile`变成空文件了，不确定是不是这个问题。

[getting-the-port-number-and-the-password](https://hextechdocs.dev/getting-started-with-the-lcu-api/#getting-the-port-number-and-the-password)

如果要用另一种办法获取`port`和`password`，用python写是这样的，希望能提供些帮助
```python
import base64
import subprocess
import requests

raw_output = subprocess.check_output(
            ['wmic', 'PROCESS', 'WHERE', "name='LeagueClientUx.exe'", 'GET', 'commandline']).decode('utf-8','ignore')
for segment in raw_output.split('" "'):
    if '--app-port' in segment:
        port = int(segment.split('=')[1])
    if '--install-directory' in segment:
        install_directory = segment.split('=')[1]
    if '--remoting-auth-token' in segment:
        password = segment.split('=')[1]

auth_key = base64.b64encode(f'riot:{password}'.encode()).decode()

def make_quest(endpoint):
    r =  requests.get(f'https://127.0.0.1:{port}{endpoint}',
            headers={'Accept': 'application/json', 'Authorization': f'Basic {auth_key}'},
            verify=False)
    return r.json()
r = make_quest('/lol-summoner/v1/current-summoner')
print(r)
```

**Comment by magicwenli** [comment]
或者像之前一样读取`<GamePath>\Game\Logs\LeagueClient Logs`下的最新`<Datetime>_LeagueClientUx.log`

这种变化有些不妙，不知道下个版本会不会继续限制开发者使用LCU接口。

**Comment by magicwenli** [comment]
手动给`lockfile`设置了正确的值，还是不行啊

```
[2021-11-18 16:24:39.714] [info]  [watcher] lcu is inactive
[2021-11-18 16:24:50.193] [info]  ChampR starting, app version 1.1.9.
[2021-11-18 16:30:02.651] [info]  [watcher] got auth
[2021-11-18 16:30:02.651] [info]  { urlWithAuth: 'https://riot:undefined@127.0.0.1:undefined' }
[2021-11-18 16:30:02.653] [error] Invalid URL: https://riot:undefined@127.0.0.1:undefined/
[2021-11-18 16:30:02.653] [info]  [watcher] get auth failed, either lcu is inactive or lol dir is incorrect
[2021-11-18 16:31:12.890] [info]  ChampR starting, app version 1.1.9.
[2021-11-18 16:32:48.755] [info]  ChampR starting, app version 1.1.9.
[2021-11-18 16:32:48.922] [info]  System locale is zh-CN, app lang is zh-CN
[2021-11-18 16:32:48.923] [info]  init lockfile watcher, dir: C:\Program Files\Tencent\League
[2021-11-18 16:32:48.967] [info]  shouldAppendGameToDir:  true lolDirHasCJKChar:  false
[2021-11-18 16:32:48.969] [info]  [watcher] got auth
[2021-11-18 16:32:48.969] [info]  {
  port: '7210',
  token: 'IOqtwuCr8IipGC-ZMghuKw',
  urlWithAuth: 'https://riot:IOqtwuCr8IipGC-ZMghuKw@127.0.0.1:7210'
}
[2021-11-18 16:32:48.982] [error] (node:18688) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `ChampR --trace-warnings ...` to show where the warning was created)
[2021-11-18 16:32:48.986] [info]  [watcher] got auth
[2021-11-18 16:32:48.987] [info]  {
  port: '7210',
  token: 'IOqtwuCr8IipGC-ZMghuKw',
  urlWithAuth: 'https://riot:IOqtwuCr8IipGC-ZMghuKw@127.0.0.1:7210'
}
[2021-11-18 16:32:48.994] [error] Unexpected server response: 401
[2021-11-18 16:32:48.996] [error] Unexpected server response: 401
[2021-11-18 16:32:48.996] [info]  [watcher] get auth failed, either lcu is inactive or lol dir is incorrect
[2021-11-18 16:32:50.145] [info]  userId: ac2248d160738772fd1ad355a2e2ba376d4233bafee6b6c448b6c39166f831a4
[2021-11-18 16:32:50.146] [info]  Checking for update
[2021-11-18 16:32:50.146] [info]  Checking update...
[2021-11-18 16:32:55.115] [info]  app sha is 6333aed

[2021-11-18 16:33:09.692] [error] Error: Error: net::ERR_CONNECTION_RESET
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
[2021-11-18 16:33:09.692] [error] Error in auto-updater. Error: net::ERR_CONNECTION_RESET
[2021-11-18 16:33:09.693] [error] Network Error

```

**Comment by cangzhang** [comment]
@magicwenli 决定用 command 的方式去获取 credentials. 尝试修复中

**Comment by LaurenceJang** [comment]
请问1.1.9版本是否解决了不能弹出窗口的bug，我这里还是不行

**Comment by chickes** [comment]
> 请问1.1.9版本是否解决了不能弹出窗口的bug，我这里还是不行

我也不行，等作者修复吧

**Comment by LaurenceJang** [comment]
> > 请问1.1.9版本是否解决了不能弹出窗口的bug，我这里还是不行
> 
> 我也不行，等作者修复吧

ok

**Comment by hqwl1985** [comment]
坐等!

**Comment by hqwl1985** [comment]
更新咯!!!!!!

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/releases/tag/v1.1.10

**Comment by chickes** [comment]
> https://github.com/cangzhang/champ-r/releases/tag/v1.1.10

ok，谢谢

**Comment by cgzhiahia** [comment]
> https://github.com/cangzhang/champ-r/releases/tag/v1.1.10

还是不能弹窗

**Comment by ieiang** [comment]
> https://github.com/cangzhang/champ-r/releases/tag/v1.1.10
您好，这个版本还是不能弹窗

**Comment by magicwenli** [comment]
> > https://github.com/cangzhang/champ-r/releases/tag/v1.1.10
> 
> 还是不能弹窗

@cgzhiahia 

> > https://github.com/cangzhang/champ-r/releases/tag/v1.1.10
> > 您好，这个版本还是不能弹窗

@ieiang 


可以提供一下日志吗? 

日志位于`%AppData%\Roaming\ChampR\logs`，将日志拖放到编辑框就可以了。

**Comment by cgzhiahia** [comment]
[main.log](https://github.com/cangzhang/champ-r/files/7573973/main.log)

**Comment by cgzhiahia** [comment]
> 
https://github.com/cangzhang/champ-r/files/7573973/main.log
[renderer.log](https://github.com/cangzhang/champ-r/files/7573974/renderer.log)

**Comment by ieiang** [comment]
[main.log](https://github.com/cangzhang/champ-r/files/7574008/main.log)
@magicwenli

**Comment by magicwenli** [comment]
完全看不出来问题在哪里。试一下重新安装吧，用管理员权限运行。

**Comment by magicwenli** [comment]
完全看不出来问题在哪里。试一下重新安装吧，用管理员权限运行。

**Comment by cgzhiahia** [comment]
> [main.log](https://github.com/cangzhang/champ-r/files/7574008/main.log) @magicwenli

我的还是没有弹窗
