### ISSUE TITLE
更新1.1.12后仍旧存在第一次游戏可以正常弹窗，第二次以及之后都不能的bug

### ISSUE THREAD

**Issue by Kotagan** [cangzhang/champ-r#121]
**Describe the bug 详细描述**
更新1.1.12后仍旧存在第一次游戏可以正常弹窗，第二次以及之后都不能的bug
根据另一个issue卸载了重装也无法解决问题
先管理员启动champ然后再启动的游戏

**Screenshots or screen record 截图或录屏**
[2021-11-25 13:45:48.558] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-25 13:45:50.634] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-25 13:45:52.550] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-25 13:45:54.565] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-25 13:45:56.576] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input

**Desktop (please complete the following information) 系统环境:**
版本	Windows 11 专业版
版本	21H2
安装日期	‎2021/‎10/‎7
操作系统版本	22000.318
体验	Windows 功能体验包 1000.22000.318.0

**Additional context 附加信息**
个人使用的是双屏，不知道有没有影响

**Comment by cangzhang** [comment]
先删配置, 再试试关掉一个屏幕会不会正常?

**Comment by cangzhang** [comment]
这个 log 不是 champr 的, 贴一下 `%appdata%/champr/logs` 目录下

**Comment by Kotagan** [comment]
> 这个 log 不是 champr 的, 贴一下 `%appdata%/champr/logs` 目录下

[2021-11-25 13:45:48.558] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-25 13:45:50.634] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-25 13:45:52.550] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-25 13:45:54.565] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-25 13:45:56.576] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input

**Comment by Kotagan** [comment]
> 这个 log 不是 champr 的, 贴一下 `%appdata%/champr/logs` 目录下

[2021-11-26 12:16:32.179] [error] (node:6616) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `ChampR --trace-warnings ...` to show where the warning was created)
[2021-11-26 12:16:37.245] [info]  [watcher] lcu is not active, connect ECONNREFUSED 127.0.0.1:5688
[2021-11-26 12:16:52.648] [info]  [watcher] lcu status changed
[2021-11-26 12:19:06.247] [info]  [watcher] picked champion 36
[2021-11-26 12:19:08.283] [info]  [watcher] picked champion 36
[2021-11-26 12:19:10.285] [info]  [watcher] picked champion 36
[2021-11-26 12:19:12.302] [info]  [watcher] picked champion 555
[2021-11-26 12:19:14.288] [info]  [watcher] picked champion 555
[2021-11-26 12:19:16.286] [info]  [watcher] picked champion 555
[2021-11-26 12:19:18.282] [info]  [watcher] picked champion 555
[2021-11-26 12:19:20.285] [info]  [watcher] picked champion 555

**Comment by cangzhang** [comment]
先打开客户端, 然后管理员权限 powershell 执行一下命令:
`Get-CimInstance Win32_Process -Filter "name = 'LeagueClientUx.exe'" | Select CommandLine | ConvertTo-Json`

看看输出了什么

**Comment by Kotagan** [comment]
> 先打开 lol 客户端, 然后管理员权限 powershell 执行一下命令: `Get-CimInstance Win32_Process -Filter "name = 'LeagueClientUx.exe'" | Select CommandLine | ConvertTo-Json`
> 
> 看看输出了什么

{
    "CommandLine":  "\"F:/LOL/Riot Games/League of Legends/LeagueClientUx.exe\" \"--riotclient-auth-token=Msx8SV__kWN9e87c1EszDQ\" \"--riotclient-app-port=1296\" \"--no-rads\" \"--disable-self-update\" \"--region=JP\" \"--locale=ja_JP\" \"--remoting-auth-token=IAWsBvguxGYRWayjm-rgCg\" \"--respawn-command=LeagueClient.exe\" \"--respawn-display-name=League of Legends\" \"--app-port=1952\" \"--install-directory=F:\\LOL\\Riot Games\\League of Legends\" \"--app-name=LeagueClient\" \"--ux-name=LeagueClientUx\" \"--ux-helper-name=LeagueClientUxHelper\" \"--log-dir=LeagueClient Logs\" \"--crash-reporting=crashpad\" \"--crash-environment=JP1\" \"--crash-pipe=\\\\.\\pipe\\crashpad_21080_CRMHZVNBRCMNMBWN\" \"--app-log-file-path=F:/LOL/Riot Games/League of Legends/Logs/LeagueClient Logs/2021-11-26T13-11-05_21080_LeagueClient.log\" \"--app-pid=21080\" \"--output-base-dir=F:\\LOL\\Riot Games\\League of Legends\" \"--no-proxy-server\""
}

**Comment by cangzhang** [comment]
> 

看起来都正常, 按照这里的试试吧

**Comment by Kotagan** [comment]
关闭双屏似乎是可以的，我再多试几把

**Comment by cangzhang** [comment]
这么看起来和双屏有关系, 我想办法再搞一块屏幕...

**Comment by sunFlying** [comment]
我没有双屏，也是第一次游戏可以正常弹窗，第二次以及之后都不能。

**Comment by sunFlying** [comment]
PS C:\Windows\system32> Get-CimInstance Win32_Process -Filter "name = 'LeagueClientUx.exe'" | Select CommandLine | ConvertTo-Json
{
    "CommandLine":  "\"c:/program files/腾讯游戏/英雄联盟/LeagueClient/LeagueClientUx.exe\" \"--riotclient-auth-token=K2Zkqc6oCwgNKnTaSES3Og\" \"--riotclient-app-port=9271\" \"--riotclient-tencent\" \"--no-rads\" \"--disable-self-update\" \"--region=TENCENT\" \"--locale=zh_CN\" \"--t.lcdshost=wt1-cloud-feapp.lol.qq.com\" \"--t.chathost=wt1-cloud-ejabberd.lol.qq.com\" \"--t.lq=https://wt1-cloud-login.lol.qq.com:8443\" \"--t.storeurl=https://wt1-cloud-sr.lol.qq.com:8443\" \"--t.rmsurl=wss://wt1-cloud-rms.lol.qq.com:443\" \"--rso-auth.url=https://prod-rso.lol.qq.com:3000\" \"--rso_platform_id=WT1_NEW\" \"--rso-auth.client=lol\" \"--t.location=loltencent.tjkg.WT1_NEW\" \"--tglog-endpoint=https://tglogsz.datamore.qq.com/lolcli/report/\" \"--t.league_edge_url=https://ledge-wt1cloud.lol.qq.com:22019\" \"--ccs=https://cc-wt1-cloud.lol.qq.com:8093\" \"--dradis-endpoint=http://some.url\" \"--remoting-auth-token=usW3xG-DJvGAQyMJYOBxAg\" \"--app-port=8489\" \"--install-directory=c:\\program files\\鑵捐娓告垙\\鑻遍泟鑱旂洘\\LeagueClient\" \"--app-name=LeagueClient\" \"--ux-name=LeagueClientUx\" \"--ux-helper-name=LeagueClientUxHelper\" \"--log-dir=LeagueClient Logs\" \"--crash-reporting=\" \"--crash-environment=WT1_NEW\" \"--app-log-file-path=c:/program files/腾讯游戏/英雄联盟/LeagueClient/../Game/Logs/LeagueClient Logs/2021-11-26T22-59-41_95872_LeagueClient.log\" \"--app-pid=95872\" \"--output-base-dir=c:/program files/鑵捐 娓告垙/鑻遍泟鑱旂洘/LeagueClient/../Game\" \"--no-proxy-server\""

**Comment by sunFlying** [comment]
PS C:\Windows\system32> Get-CimInstance Win32_Process -Filter "name = 'LeagueClientUx.exe'" | Select CommandLine | ConvertTo-Json
{
    "CommandLine":  "\"c:/program files/腾讯游戏/英雄联盟/LeagueClient/LeagueClientUx.exe\" \"--riotclient-auth-token=K2Zkqc6oCwgNKnTaSES3Og\" \"--riotclient-app-port=9271\" \"--riotclient-tencent\" \"--no-rads\" \"--disable-self-update\" \"--region=TENCENT\" \"--locale=zh_CN\" \"--t.lcdshost=wt1-cloud-feapp.lol.qq.com\" \"--t.chathost=wt1-cloud-ejabberd.lol.qq.com\" \"--t.lq=https://wt1-cloud-login.lol.qq.com:8443\" \"--t.storeurl=https://wt1-cloud-sr.lol.qq.com:8443\" \"--t.rmsurl=wss://wt1-cloud-rms.lol.qq.com:443\" \"--rso-auth.url=https://prod-rso.lol.qq.com:3000\" \"--rso_platform_id=WT1_NEW\" \"--rso-auth.client=lol\" \"--t.location=loltencent.tjkg.WT1_NEW\" \"--tglog-endpoint=https://tglogsz.datamore.qq.com/lolcli/report/\" \"--t.league_edge_url=https://ledge-wt1cloud.lol.qq.com:22019\" \"--ccs=https://cc-wt1-cloud.lol.qq.com:8093\" \"--dradis-endpoint=http://some.url\" \"--remoting-auth-token=usW3xG-DJvGAQyMJYOBxAg\" \"--app-port=8489\" \"--install-directory=c:\\program files\\鑵捐娓告垙\\鑻遍泟鑱旂洘\\LeagueClient\" \"--app-name=LeagueClient\" \"--ux-name=LeagueClientUx\" \"--ux-helper-name=LeagueClientUxHelper\" \"--log-dir=LeagueClient Logs\" \"--crash-reporting=\" \"--crash-environment=WT1_NEW\" \"--app-log-file-path=c:/program files/腾讯游戏/英雄联盟/LeagueClient/../Game/Logs/LeagueClient Logs/2021-11-26T22-59-41_95872_LeagueClient.log\" \"--app-pid=95872\" \"--output-base-dir=c:/program files/鑵捐 娓告垙/鑻遍泟鑱旂洘/LeagueClient/../Game\" \"--no-proxy-server\""
}

**Comment by sunFlying** [comment]
我也不是win11，我是win10

**Comment by sunFlying** [comment]
[2021-11-25 23:37:43.370] [warn]  [watcher] [cmd] lcu is not active Command failed: Get-CimInstance Win32_Process -Filter "name = 'LeagueClientUx.exe'" | Select CommandLine | ConvertTo-Json

[2021-11-25 23:37:46.862] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:58:58.596] [info]  ChampR starting, app version 1.1.12.
[2021-11-26 22:59:03.918] [info]  System locale is zh-CN, app lang is zh-CN
[2021-11-26 22:59:09.926] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:59:09.931] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:59:10.730] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:59:12.838] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:59:15.072] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:59:16.892] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:59:18.874] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:59:22.140] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:59:27.845] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:59:27.908] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:59:29.725] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:59:30.902] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:59:32.212] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:59:33.178] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:59:35.004] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:59:39.672] [info]  userId: 16911e2f63c1550202b1e7e5370dc9135386cbd25d57893e985605069f855f4c
[2021-11-26 22:59:39.674] [info]  Checking for update
[2021-11-26 22:59:39.676] [info]  Checking update...
[2021-11-26 22:59:41.190] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:59:42.466] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:59:43.441] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:59:45.581] [info]  https://riot:usW3xG-DJvGAQyMJYOBxAg@127.0.0.1:8489
[2021-11-26 22:59:48.441] [info]  Update for version 1.1.12 is not available (latest version: 1.1.12, downgrade is disallowed).
[2021-11-26 22:59:48.443] [error] Update not available: 1.1.12
[2021-11-26 22:59:48.531] [error] (node:88956) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `ChampR --trace-warnings ...` to show where the warning was created)
[2021-11-26 22:59:53.699] [info]  [watcher] lcu status changed

**Comment by sunFlying** [comment]
我还发现一个现象，当我第一次打开一个自定义选人界面，会弹窗；而且，我退出选人，不进入游戏，再次进入选人阶段时还是会弹窗；
但是我一旦，进入游戏了，在退出游戏，回到客户端，再次选人，就不弹窗了；
我是低配机器，应该是在哪里勾选过，进入游戏自动关闭登录客户端。这个具体我忘记哪里勾选的了。然后这个的log我贴在下一楼

**Comment by sunFlying** [comment]
[2021-11-26 22:59:41.190] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:59:42.466] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:59:43.441] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 22:59:45.581] [info]  https://riot:usW3xG-DJvGAQyMJYOBxAg@127.0.0.1:8489
[2021-11-26 22:59:48.441] [info]  Update for version 1.1.12 is not available (latest version: 1.1.12, downgrade is disallowed).
[2021-11-26 22:59:48.443] [error] Update not available: 1.1.12
[2021-11-26 22:59:48.531] [error] (node:88956) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `ChampR --trace-warnings ...` to show where the warning was created)
[2021-11-26 22:59:53.699] [info]  [watcher] lcu status changed
[2021-11-26 23:05:41.335] [info]  [watcher] picked champion 523
[2021-11-26 23:05:43.393] [info]  [watcher] picked champion 523
[2021-11-26 23:05:45.397] [info]  [watcher] picked champion 523
[2021-11-26 23:06:07.200] [info]  [watcher] picked champion 115
[2021-11-26 23:06:09.209] [info]  [watcher] picked champion 115
[2021-11-26 23:06:11.221] [info]  [watcher] picked champion 115
[2021-11-26 23:06:13.223] [info]  [watcher] picked champion 115
[2021-11-26 23:06:15.230] [info]  [watcher] picked champion 115
[2021-11-26 23:06:17.254] [info]  [watcher] picked champion 115
[2021-11-26 23:06:19.253] [info]  [watcher] picked champion 115
[2021-11-26 23:06:21.263] [info]  [watcher] picked champion 115
[2021-11-26 23:06:23.261] [info]  [watcher] picked champion 115
[2021-11-26 23:06:25.276] [info]  [watcher] picked champion 115
[2021-11-26 23:06:27.295] [info]  [watcher] picked champion 115
[2021-11-26 23:06:48.111] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-26 23:08:04.561] [info]  [watcher] lcu is not active, connect ECONNREFUSED 127.0.0.1:8489
[2021-11-26 23:08:07.961] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input

**Comment by sunFlying** [comment]
![image](https://user-images.githubusercontent.com/16077886/143601660-b529f3ea-998c-420d-bb1b-a9b2e3d5cafb.png)

**Comment by sunFlying** [comment]
![image](https://user-images.githubusercontent.com/16077886/143601790-9d197ed8-5033-4cff-9c50-297961896b1b.png)

**Comment by sunFlying** [comment]
@cangzhang  @Kotagan 我试了一下，关闭这个选项就没有问题了。希望对大家有帮助

**Comment by cangzhang** [comment]
@sunFlying 非常有用的信息, 👍

**Comment by ericgidseg** [comment]
进入游戏不显示配装方案，卸载重装软件或游戏都是，win11正式版。
[2021-11-27 16:20:53.231] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-27 16:20:53.813] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-27 16:20:55.800] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-27 16:20:57.858] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-27 16:20:59.862] [info]  https://riot:l_Q-4eI1gENFDkUsQysbvw@127.0.0.1:59100
[2021-11-27 16:21:01.893] [error] (node:7776) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `ChampR --trace-warnings ...` to show where the warning was created)
[2021-11-27 16:21:07.038] [info]  [watcher] lcu is not active, Response code 503 (Service Unavailable)
[2021-11-27 16:21:23.114] [info]  lolDir is E:\WeGameApps\英雄联盟
[2021-11-27 16:21:53.034] [info]  [watcher] lcu status changed
[2021-11-27 16:21:55.760] [info]  [watcher] picked champion 39
[2021-11-27 16:21:57.076] [info]  [watcher] picked champion 39
[2021-11-27 16:21:59.088] [info]  [watcher] picked champion 39
[2021-11-27 16:22:01.136] [info]  [watcher] picked champion 39
[2021-11-27 16:22:03.133] [info]  [watcher] picked champion 39
[2021-11-27 16:22:05.139] [info]  [watcher] picked champion 39
[2021-11-27 16:22:07.139] [info]  [watcher] picked champion 39
[2021-11-27 16:22:09.151] [info]  [watcher] picked champion 39
[2021-11-27 16:22:11.159] [info]  [watcher] picked champion 39
[2021-11-27 16:22:13.167] [info]  [watcher] picked champion 39
[2021-11-27 16:22:15.176] [info]  [watcher] picked champion 39
[2021-11-27 16:22:17.184] [info]  [watcher] picked champion 39
[2021-11-27 16:22:19.237] [info]  [watcher] picked champion 39
[2021-11-27 16:22:21.240] [info]  [watcher] picked champion 39
[2021-11-27 16:22:23.245] [info]  [watcher] picked champion 39
[2021-11-27 16:22:25.261] [info]  [watcher] picked champion 39
[2021-11-27 16:22:27.262] [info]  [watcher] picked champion 39
[2021-11-27 16:22:29.271] [info]  [watcher] picked champion 39
[2021-11-27 16:22:31.321] [info]  [watcher] picked champion 39
[2021-11-27 16:22:33.332] [info]  [watcher] picked champion 39
[2021-11-27 16:22:35.363] [info]  [watcher] picked champion 39
[2021-11-27 16:22:59.050] [warn]  [watcher] [cmd] lcu is not active Unexpected end of JSON input
[2021-11-27 16:24:29.754] [info]  ChampR starting, app version 1.1.12.
[2021-11-27 16:24:29.883] [info]  System locale is zh-CN, app lang is zh-CN
[2021-11-27 16:24:31.323] [info]  userId: 72466e351f7472b2dad2b219b70930283d6fd49ba58c00aa92ea2ead1996c5ba
[2021-11-27 16:24:31.324] [info]  Checking for update
[2021-11-27 16:24:31.324] [info]  Checking update...
[2021-11-27 16:24:32.296] [info]  https://riot:l_Q-4eI1gENFDkUsQysbvw@127.0.0.1:59100
[2021-11-27 16:24:33.203] [info]  Update for version 1.1.12 is not available (latest version: 1.1.12, downgrade is disallowed).
[2021-11-27 16:24:33.204] [error] Update not available: 1.1.12
[2021-11-27 16:24:34.313] [error] (node:17460) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `ChampR --trace-warnings ...` to show where the warning was created)
[2021-11-27 16:24:35.558] [info]  app sha is f1f8e54

**Comment by ericgidseg** [comment]
![Uploading A573EE48-A988-41A9-8481-A594006F1C46.jpeg…]()

**Comment by ericgidseg** [comment]
![B653C7CD-EB65-4A0F-967B-709B4B8436F4](https://user-images.githubusercontent.com/62279163/143674337-733c30dc-40c2-4aab-8a67-4ba5ef7cebc8.jpeg)

**Comment by cangzhang** [comment]
@ericgidseg 你是 nga 的水友吧? 感觉可能和 wegame 有关系. 试试用官方下载器安装一下 lol ?

**Comment by Criticalyes** [comment]
研究了一晚上，应该是这里没有配装方案的原因，你试试随便建一个方案看看
![image](https://user-images.githubusercontent.com/12853430/143720088-f01bc6f7-15ea-4180-8c4e-1ca532afa291.png)

**Comment by ericgidseg** [comment]
官方下载器严重限速，新建配装方案也不行

**Comment by cangzhang** [comment]
> 官方下载器严重限速，新建配装方案也不行

感觉和你的文件夹权限有关系, 是不是改过权限相关的东西? 还是重装吧. 除了你之外我没有收到别人关于出装不可见的反馈

**Comment by ericgidseg** [comment]
嗯，我再搞搞

**Comment by ericgidseg** [comment]
目录选择英雄联盟下级目录game就好了。
如: C:\Program Files\英雄联盟\Game

**Comment by anakin777** [comment]
我1.11正常，更新1.12后无法弹出

**Comment by anakin777** [comment]
@cangzhang

**Comment by cangzhang** [comment]
@anakin777 https://github.com/cangzhang/champ-r/issues/119#issuecomment-974823593

**Comment by anakin777** [comment]
> powershell



> @anakin777 [#119 (comment)](https://github.com/cangzhang/champ-r/issues/119#issuecomment-974823593)

[2021-11-28 18:52:36.249] [warn]  [watcher] [cmd] lcu is not active spawn powershell.exe ENOENT
[2021-11-28 18:52:38.250] [warn]  [watcher] [cmd] lcu is not active spawn powershell.exe ENOENT
[2021-11-28 18:52:40.251] [warn]  [watcher] [cmd] lcu is not active spawn powershell.exe ENOENT
[2021-11-28 18:52:42.252] [warn]  [watcher] [cmd] lcu is not active spawn powershell.exe ENOENT

我这是这样

**Comment by Kotagan** [comment]
[2021-12-01 23:02:24.371] [error] [ps]  SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getAuthFromPs (C:\Program Files\ChampR\resources\app.asar\build\utils\lcu.js:88:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async LcuWatcher.getAuthFromCmd (C:\Program Files\ChampR\resources\app.asar\build\utils\lcu.js:162:28)
    at async Timeout._onTimeout (C:\Program Files\ChampR\resources\app.asar\build\utils\lcu.js:137:17)
[2021-12-01 23:02:24.374] [warn]  [watcher] fetch lcu status failed
[2021-12-01 23:02:26.650] [error] [cmd]  û�п���ʵ����


[2021-12-01 23:02:26.968] [error] [ps]  SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getAuthFromPs (C:\Program Files\ChampR\resources\app.asar\build\utils\lcu.js:88:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async LcuWatcher.getAuthFromCmd (C:\Program Files\ChampR\resources\app.asar\build\utils\lcu.js:162:28)
    at async Timeout._onTimeout (C:\Program Files\ChampR\resources\app.asar\build\utils\lcu.js:137:17)
[2021-12-01 23:02:26.968] [warn]  [watcher] fetch lcu status failed
[2021-12-01 23:02:29.234] [error] [cmd]  û�п���ʵ����
