### ISSUE TITLE
can't yarn run build:local on linux

### ISSUE THREAD

**Issue by PhYdrogen** [cangzhang/champ-r#20]
i can `yarn start` it execute normaly ? (it open with the inspector and when i select my champ nothing happen)
and when i want to build it i got this output >

    hydrogenmk8@pop-os-mk8:~/Programs/champ-r-0.9.14$ sudo npm run build
    champ-r@0.9.14 build /home/hydrogenmk8/Programs/champ-r-0.9.14`
    cross-env yarn build-react && yarn dist`

    yarn run v1.22.4
    $ node scripts/build.js
    fatal: ni ceci ni aucun de ses répertoires parents n'est un dépôt git : .git
    child_process.js:669
        throw err;
        ^

    Error: Command failed: git rev-parse --short HEAD
    fatal: ni ceci ni aucun de ses répertoires parents n'est un dépôt git : .git

    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at getClientEnvironment (/home/hydrogenmk8/Programs/champ-r-0.9.14/config/env.js:71:8)
    at module.exports (/home/hydrogenmk8/Programs/champ-r-0.9.14/config/webpack.config.js:80:15)
    at Object.<anonymous> (/home/hydrogenmk8/Programs/champ-r-0.9.14/scripts/build.js:46:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! champ-r@0.9.14 build: `cross-env yarn build-react && yarn dist`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the champ-r@0.9.14 build script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2020-07-11T12_04_03_333Z-debug.log

**Comment by cangzhang** [comment]
You need specify [linux build config](https://www.electron.build/configuration/linux) for `electron-builder` first.

**Comment by PhYdrogen** [comment]
so i read the doc, i modify the package.json and i ran `yarn electron-builder build` and i got dist/ file and a deb package

**Comment by PhYdrogen** [comment]
when i launch it i have an error 
Unhandled Promise Rejection
Error: ERR_FILE_NOT_FOUND (-6) loading 'file:///opt/ChampR/resources/app.asar/build/index.html'
    at rejectAndCleanup (electron/js2c/browser_init.js:6026:21)
    at WebContents.failListener (electron/js2c/browser_init.js:6036:11)

**Comment by PhYdrogen** [comment]
i can't make it work nvm
