### ISSUE TITLE
您好，我的champr不能弹窗

### ISSUE THREAD

**Issue by CH-dream** [cangzhang/champ-r#201]
安装完成后无法弹出选择游戏目录的弹窗，但是任务管理器有三个champr任务在运行，我个人电脑安装的是网吧无盘系统
以下是报错信息
[2022-08-21 13:09:31.559] [error] Error: ERR_FAILED (-2) loading 'file://Y:\游戏辅助\ChampR\resources\app.asar\build\index.html'
    at rejectAndCleanup (electron/js2c/browser_init.js:213:985)
    at Object.stopLoadingListener (electron/js2c/browser_init.js:213:1360)
    at Object.emit (events.js:327:22)
[2022-08-21 13:09:31.846] [warn]  [watcher] fetch lcu status failed
[2022-08-21 13:09:40.985] [info]  ChampR starting, app version 1.3.2.
[2022-08-21 13:09:41.173] [info]  System locale is zh-CN, app lang is zh-CN
[2022-08-21 13:09:41.252] [info]  powershell: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe

[2022-08-21 13:09:41.253] [info]  creating main window...
[2022-08-21 13:09:44.494] [warn]  [watcher] fetch lcu status failed
[2022-08-21 13:09:47.755] [warn]  [watcher] fetch lcu status failed

系统是
版本	Windows 10 专业版
版本号	21H1
安装日期	‎2021/‎8/‎25/‎周三
操作系统内部版本	19043.1165
体验	Windows Feature Experience Pack 120.2212.3530.0

**Comment by cangzhang** [comment]
ChampR 所有的功能都是基于官方原版系统开发的, 换用官方原版试试
