### ISSUE TITLE
1.1.4版本无法弹窗，卸载重下也一样。

### ISSUE THREAD

**Issue by ganisy** [cangzhang/champ-r#82]
**Describe the bug 详细描述**

**Screenshots or screen record 截图或录屏**

**Desktop (please complete the following information) 系统环境:**

**Additional context 附加信息**

**Comment by cangzhang** [comment]
是国服吗？
导入的出装可以在游戏里看到吗？

**Comment by AUZQ** [comment]
> 是国服吗？
> 导入的出装可以在游戏里看到吗？

出装看得到，但是天赋不弹窗

**Comment by xxbash** [comment]
有同样的问题，游戏版本11.17 软件版本1.14无选英雄的时候没弹窗

**Comment by bakamoon** [comment]
![程序未显示](https://user-images.githubusercontent.com/89714943/132100450-38d591e5-14f7-4196-917b-e6e031d9a181.png)
。安装1.1.4以后任务管理器能看到程序，但是右下角和主界面并没有弹出程序

**Comment by yzlyu** [comment]
我是有弹窗 但是一直转圈圈~~
![image](https://user-images.githubusercontent.com/9254175/132107235-ef0149bb-0e02-4a65-88ba-20dce7bb9a13.png)

**Comment by yzlyu** [comment]
> 我是有弹窗 但是一直转圈圈~~
> ![image](https://user-images.githubusercontent.com/9254175/132107235-ef0149bb-0e02-4a65-88ba-20dce7bb9a13.png)

重装了1.2、1.3，再装1.4之后 就好了，很玄学。谢谢作者！

**Comment by cangzhang** [comment]
@xxbash 发一下自己的日志看看？在这个文件夹 `%APPDATA%/ChampR/logs`

**Comment by cangzhang** [comment]
@bakamoon 试试在任务管理器里面干掉再重新打开

**Comment by bakamoon** [comment]
> @bakamoon聪明在任务管理器里面干掉再重新打开
试过了。一路版本重新安装过去后，只有1.0.3的能显示导入出装主界面，但是选英雄的时候不会弹出天赋窗了，重装好几遍都没有用。。已经是管理员启动了

**Comment by cangzhang** [comment]
@bakamoon windows 10 的版本是多少？

**Comment by bakamoon** [comment]
> @bakamoon windows 10 的版本是多少？

![1](https://user-images.githubusercontent.com/89714943/132112819-e9dd84bc-40ba-42ca-998c-2648467d3500.png)
emmmm。卧槽这是啥版本。。

**Comment by cangzhang** [comment]
> > @bakamoon windows 10 的版本是多少？
> 
> ![1](https://user-images.githubusercontent.com/89714943/132112819-e9dd84bc-40ba-42ca-998c-2648467d3500.png)
> emmmm。卧槽这是啥版本。。

![image](https://user-images.githubusercontent.com/1357073/132113090-25553bdc-c16c-41bb-82a8-c4a4593d35e3.png)

**Comment by bakamoon** [comment]
@cangzhang 
![2](https://user-images.githubusercontent.com/89714943/132113488-6fa64a32-8b42-416f-9601-125b58320524.png)

**Comment by cangzhang** [comment]
@bakamoon 更新到 1903 之后的版本
https://www.microsoft.com/zh-cn/software-download/windows10

**Comment by cangzhang** [comment]
@yzlyu 你碰到的只是网络问题，重新打开一次 champr 应该就可以了。

**Comment by KirinRyuuri** [comment]
> @xxbash 导入出装之后，可以看到出装吗？
> 如果可以看到出装但是没有天赋弹窗的话，发一下自己的日志看看？在这个文件夹 `%APPDATA%/ChampR/logs`

我也遇到了天赋弹窗不出来的问题，装备导入功能正常
OS：Windows 10 专业版 20H2 19042.1165
Version： 1.14,
确认是管理员权限启动，而且没装WeGame...（有Champ-r要什么WeGame

在 `main.log` 里面没有看到相关的日志，只有 `auto-updater` 的错误日志
在 `renderer.log` 里面看到了以下几个重复次数很多的日志，没有更多的日志
```log
[2021-08-29 20:36:48.131] [info] shouldAppendGameToDir 1630235661261.7615
[2021-08-29 20:36:50.020] [error] lcu not running. ### 这条日志重复多次
[2021-08-29 20:36:57.716] [error] Request failed with status code 404 Error: Request failed with status code 404
    at e.exports (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/0.b138c8f3.chunk.js:5:253623)
    at e.exports (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/0.b138c8f3.chunk.js:8:168567)
    at XMLHttpRequest.f.onreadystatechange (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/0.b138c8f3.chunk.js:5:252474)
[2021-08-29 20:36:57.717] [error] Error: Request failed with status code 404 Error: Error: Request failed with status code 404
    at l.getChampionDataFromCdn (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/main.3706289e.chunk.js:1:120832)
    at async l.genItemBuilds (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/main.3706289e.chunk.js:1:120987)
### 下面这两条日志一直在多次重复 ###
[2021-08-29 20:37:38.930] [error] Network Error Error: Network Error
    at e.exports (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/0.b138c8f3.chunk.js:5:253623)
    at XMLHttpRequest.f.onerror (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/0.b138c8f3.chunk.js:5:252592)
[2021-08-29 20:37:38.931] [error] Error: Network Error Error: Error: Network Error
    at l.getChampionDataFromCdn (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/main.3706289e.chunk.js:1:120832)
    at async l.genItemBuilds (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/main.3706289e.chunk.js:1:120987)
### 上面这两条日志一直在多次重复 ###
[2021-08-29 20:37:54.241] [error] lcu not running. ### 这条日志重复多次
### 
```

下面的日志与上面已知的日志不相同

```log
[2021-08-29 20:37:55.073] [error] Request failed with status code 504 Error: Request failed with status code 504
    at e.exports (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/0.b138c8f3.chunk.js:5:253623)
    at e.exports (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/0.b138c8f3.chunk.js:8:168567)
    at XMLHttpRequest.f.onreadystatechange (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/0.b138c8f3.chunk.js:5:252474)
[2021-08-29 20:37:55.074] [error] Error: Request failed with status code 504 Error: Error: Request failed with status code 504
    at l.getChampionDataFromCdn (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/main.3706289e.chunk.js:1:120832)
    at async l.genItemBuilds (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/main.3706289e.chunk.js:1:120987)
[2021-08-29 20:37:55.074] [error] Request failed with status code 504 Error: Request failed with status code 504
    at e.exports (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/0.b138c8f3.chunk.js:5:253623)
    at e.exports (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/0.b138c8f3.chunk.js:8:168567)
    at XMLHttpRequest.f.onreadystatechange (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/0.b138c8f3.chunk.js:5:252474)
[2021-08-29 20:37:55.075] [error] Error: Request failed with status code 504 Error: Error: Request failed with status code 504
    at l.getChampionDataFromCdn (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/main.3706289e.chunk.js:1:120832)
    at async l.genItemBuilds (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/main.3706289e.chunk.js:1:120987)
[2021-08-29 20:37:55.992] [error] Request failed with status code 504 Error: Request failed with status code 504
    at e.exports (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/0.b138c8f3.chunk.js:5:253623)
    at e.exports (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/0.b138c8f3.chunk.js:8:168567)
    at XMLHttpRequest.f.onreadystatechange (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/0.b138c8f3.chunk.js:5:252474)
[2021-08-29 20:37:55.993] [error] Error: Request failed with status code 504 Error: Error: Request failed with status code 504
    at l.getChampionDataFromCdn (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/main.3706289e.chunk.js:1:120832)
    at async l.genItemBuilds (file:///C:/Users/Kirin/AppData/Local/Programs/champ-r/resources/app.asar/build/static/js/main.3706289e.chunk.js:1:120987)
[2021-08-29 20:37:58.400] [info] shouldAppendGameToDir 1630235661261.7615
```
基本上就上面两种日志重复打印，如果需要完整日志可以再联系（就是一些重复的日志内容，我觉得没有什么参考价值...）

---
PS：@bakamoon 你那个明显是XX一键装机的win10版本...

**Comment by bakamoon** [comment]
@cangzhang @KirinRyuuri 没错。。。是没更新的问题。。。整了一天差点重装终于弄好了。。是系统版本太低了

**Comment by cangzhang** [comment]
@KirinRyuuri 从日志上看是你的本地网络访问不到 cdn，可以试试把 `https://cdn.jsdelivr.net` 放到代理规则里去

**Comment by KirinRyuuri** [comment]
> @KirinRyuuri ~从日志上看是你的本地网络访问不到 cdn，可以试试把 `https://cdn.jsdelivr.net` 放到代理规则里去~
> 
> 看来是没能正常访问到英雄联盟安装目录下的文件。
> `{英雄联盟安装目录}\Game\Logs\LeagueClient Logs` 目录下有内容吗，你玩的服务器是国服不？
---

的确是国服，不过现在我的问题已经解决了 ~（应该是GitHub被墙了的原因）~
之前用的 1.13 版本的时候弹窗更新 1.14 ，但是我不知道为什么更新没有成功
之后就再没有提示更新，所以我以为是更新完成了 ~（实际上可能没有更新吧）~
---
最后我卸载重装了一遍就正常了

**Comment by cangzhang** [comment]
@KirinRyuuri 用的基础组件的问题，经常会出现资源没有及时替换的情况。我思考一下，在之后的版本里解决这种问题

**Comment by xxbash** [comment]
> @xxbash导入出装之后，可以看到出装吗？
> 如果可以看到出装但是没有天赋弹窗的话，发一下自己的日志看看？在这个文件夹`%APPDATA%/ChampR/logs`

[main.log](https://github.com/cangzhang/champ-r/files/7111644/main.log)
[renderer.log](https://github.com/cangzhang/champ-r/files/7111645/renderer.log)
[renderer.old.log](https://github.com/cangzhang/champ-r/files/7111646/renderer.old.log)
这是我这个文件夹内的3个log
系统版本
![image](https://user-images.githubusercontent.com/22096104/132128106-32bd7064-5a5c-41ec-9a86-2719206f0056.png)

**Comment by cangzhang** [comment]
@xxbash 试试先卸载再重新安装最新版本

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/releases/tag/v1.1.5
